/remoll/setgeofile geometry/mollerMother.gdml
/remoll/physlist/register QGSP_BERT_HP
/remoll/physlist/parallel/enable
/remoll/parallel/setfile geometry/mollerParallel.gdml
/run/numberOfThreads 5
/run/initialize
/remoll/addfield map_directory/V2DSg.9.75cm.parallel.txt
/remoll/addfield map_directory/V2U.1a.50cm.parallel.txt
/remoll/evgen/set external
/remoll/evgen/external/file /work/halla/moller12gev/palatchi/moller/remoll/rootfiles/o_remollSkimTree1004.root
/remoll/evgen/external/detid 1004
/remoll/evgen/external/zOffset 0.001 # backoff trajectory by 1 mm. Don't back off too much though. Unit is in mm.
/remoll/SD/disable_all
/remoll/SD/enable 1004
/remoll/SD/detect lowenergyneutral 1004
/remoll/SD/detect secondaries 1004
/remoll/SD/detect boundaryhits 1004
/remoll/SD/enable 28
/remoll/SD/detect lowenergyneutral 28
/remoll/SD/detect secondaries 28
/remoll/SD/detect boundaryhits 28

#/remoll/kryptonite/volume lefthut_Det_inside_logic
/remoll/kryptonite/enable
/remoll/filename remollout_test1004.root
/run/beamOn 50
#/run/beamOn 42353     #If this number is bigger than the exact number of entries in b1.root, the simulation will loop over from the first event again. 

