#/remoll/geometry/setfile geometry/mollerMother.gdml
/remoll/setgeofile geometry/mollerMother.gdml

#/remoll/parallel/setfile geometry/mollerParallel.gdml 
/remoll/parallel/setfile geometry/mollerParallel.gdml 

/remoll/physlist/parallel/enable 

/run/initialize

/remoll/printgeometry true

#/control/execute macros/load_magnetic_fieldmaps.mac
/remoll/addfield map_directory/V2DSg.9.75cm.parallel.txt
/remoll/addfield map_directory/V2U.1a.50cm.parallel.txt

#/remoll/oldras true

/remoll/evgen/beam/origin 0 0 -7.5 m

#/remoll/rasx 5 mm
/remoll/evgen/beam/rasx 5 mm

#/remoll/rasy 5 mm
/remoll/evgen/beam/rasy 5 mm

/remoll/evgen/beam/corrx 0.065

/remoll/evgen/beam/corry 0.065

/remoll/evgen/beam/rasrefz -4.5 m

/remoll/beamene 11 GeV

#/remoll/beamcurr 85 microampere
/remoll/beamcurr 65 microampere

/remoll/evgen/set beam

/remoll/evgen/beamPolarization +L
/remoll/field/equationtype 2
/remoll/field/steppertype 2
/remoll/field/print

/remoll/SD/disable_all
/remoll/SD/enable 28
/remoll/SD/detect lowenergyneutral 28
/remoll/SD/detect secondaries 28
/remoll/SD/detect boundaryhits 28

#/control/execute macros/kryptonite.mac
/remoll/kryptonite/enable
/remoll/kryptonite/add VacuumKryptonite
/remoll/kryptonite/add Tungsten
/remoll/kryptonite/add Copper
/remoll/kryptonite/add Lead
/remoll/kryptonite/add CW95
/remoll/kryptonite/list

/process/list

/remoll/seed 123456

/remoll/filename testout.root

/remoll/printtargetinfo

/run/beamOn 1000
